# Generated by Django 3.1.4 on 2021-04-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(blank=True, default=None)),
                ('pagesize', models.IntegerField(blank=True, default=None)),
                ('fromdate', models.DateField(blank=True, default=None)),
                ('todate', models.DateField(blank=True, default=None)),
                ('order', models.CharField(blank=True, choices=[('1', 'votes'), ('2', 'relevance')], default=None, max_length=30)),
                ('min', models.IntegerField(blank=True, default=None)),
                ('max', models.IntegerField(blank=True, default=None)),
                ('sort', models.CharField(blank=True, choices=[('1', 'desc'), ('2', 'asc')], default=None, max_length=30)),
                ('q', models.CharField(blank=True, default=None, max_length=1000)),
                ('accepted', models.BooleanField(default=False)),
                ('answers', models.IntegerField(blank=True, default=None)),
                ('body', models.CharField(blank=True, default=None, max_length=1000)),
                ('closed', models.BooleanField(default=False)),
                ('migrated', models.BooleanField(default=False)),
                ('notice', models.BooleanField(default=False)),
                ('nottagged', models.CharField(blank=True, default=None, max_length=1000)),
                ('tagged', models.CharField(blank=True, default=None, max_length=1000)),
                ('title', models.CharField(blank=True, default=None, max_length=1000)),
                ('user', models.IntegerField(blank=True, default=None)),
                ('url', models.CharField(blank=True, default=None, max_length=1000)),
                ('views', models.IntegerField(blank=True, default=None)),
                ('wiki', models.BooleanField(default=False)),
            ],
        ),
    ]
