# Generated by Django 3.1.4 on 2021-04-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='accepted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='answers',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='body',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='closed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='fromdate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='max',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='migrated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='min',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='notice',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='nottagged',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='order',
            field=models.CharField(blank=True, choices=[('1', 'votes'), ('2', 'relevance')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='page',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='pagesize',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='q',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='sort',
            field=models.CharField(blank=True, choices=[('1', 'desc'), ('2', 'asc')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='tagged',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='todate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='user',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='views',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='wiki',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
