# Generated by Django 3.1.4 on 2021-04-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20210409_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='max',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='min',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
